#!/bin/sh
# Generates Generated/BuiltinServices.generated.h at build time (runs as a
# `before-all::` step in the Makefiles). The file imports every built-in
# service header and aggregates their PUSHER_SERVICE_* name macros into
# BUILTIN_PUSHER_SERVICES, so neither the import list nor the registry list
# ever needs to be maintained by hand -- declaring the name macro in a
# service's own header is enough to put it on both.

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
SERVICES_DIR="$ROOT_DIR/Core/Services"
OUT_FILE="$ROOT_DIR/Generated/BuiltinServices.generated.h"
TMP_FILE="$OUT_FILE.tmp"

mkdir -p "$(dirname "$OUT_FILE")"

# Name macro: the first `#define PUSHER_SERVICE_X @"..."` in each header is
# that service's name; _URL/_APP_ID and any other variants follow it and are
# intentionally ignored.
name_awk='
  /^[[:space:]]*#define[[:space:]]+PUSHER_SERVICE_[A-Z0-9_]+[[:space:]]+@"/ {
    print $2
    exit
  }
'

{
  printf '// Code generated by scripts/generate_builtin_services.sh. DO NOT EDIT.\n'
  printf '// Imports every built-in service header and aggregates their name\n'
  printf '// macros into BUILTIN_PUSHER_SERVICES at build time.\n'

  names=
  for f in "$SERVICES_DIR"/NSP*Service.h; do
    file_names=$(awk "$name_awk" "$f")
    if [ -n "$file_names" ]; then
      # Relative to this file's own location (Generated/), so quoted imports
      # resolve to Core/Services no matter which subproject includes it.
      printf '#import "../Core/Services/%s"\n' "$(basename "$f")"
      names="$names
$file_names"
    fi
  done

  sorted=$(printf '%s\n' "$names" | sed '/^$/d' | sort)
  total=$(printf '%s\n' "$sorted" | wc -l | tr -d ' ')
  if [ "$total" -eq 0 ]; then
    echo "error: no PUSHER_SERVICE_* name macros found in $SERVICES_DIR" >&2
    exit 1
  fi

  printf '\n'
  printf '#define BUILTIN_PUSHER_SERVICES                                 \\\n'
  printf '  @[                                                            \\\n'
  count=0
  for name in $sorted; do
    count=$((count + 1))
    if [ "$count" -eq "$total" ]; then
      printf '    %-40s\\\n' "$name"
    else
      printf '    %-40s\\\n' "$name,"
    fi
  done
  printf '  ]\n'
} > "$TMP_FILE"

if cmp -s "$TMP_FILE" "$OUT_FILE"; then
  rm -f "$TMP_FILE"
else
  mv "$TMP_FILE" "$OUT_FILE"
  echo "generated $OUT_FILE"
fi