name: Release

on:
  push:
    tags:
     - 'v*'

  release:
    types:
      - created

jobs:
  build:
    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Check cache
      id: verify-cache
      run: |
        echo "::set-output name=heads::`git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/xybp888/iOS-SDKs | head -n 1 | cut -f 1`"
    - name: Use cache
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/theos
        key: ${{ runner.os }}-${{ steps.verify-cache.outputs.heads }}

    - name: Prepare Theos
      uses: Randomblock1/theos-action@v1

    - name: Prepare AltList
      run: |
        git clone https://github.com/opa334/AltList.git
        cd AltList
        chmod +x install_to_theos.sh && ./install_to_theos.sh
        mkdir -p $THEOS/include/AltList
        cp AltList.h $THEOS/include/AltList/
        cd ..

    - name: Patch PSSpecifier
      run: |
        sed -i '' 's/SEL action;/SEL action;\n\tSEL setter;\n\tSEL getter;/' $THEOS/vendor/include/Preferences/PSSpecifier.h

    - name: Build package
      run: |
        rm -f packages/*
        make package FINALPACKAGE=1
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ github.workspace }}/packages/*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
